language: ruby
rvm:
  - 1.9.3
  - 2.2.5
  - jruby-1.7.25
  - jruby-9.1.5.0
  - rbx-2.1.1
  - ruby-head
jdk:
  - openjdk8 # for jruby
before_install:
  - gem install bundler || gem install bundler --version '<2'
matrix:
  allow_failures:
    - rvm: rbx-2.1.1
    - rvm: ruby-head
notifications:
  irc: "irc.freenode.org#adhearsion"
